/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n9.0.2-8-gb135b25c19-20260925"
#endif /* AVUTIL_FFVERSION_H */
